apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-ts-awesome-api
spec:
  project: default
  source:
    repoURL: https://github.com/andrewsdeon/ts-awesome-api-infra.git
    path: helm/ts-awesome-api
    targetRevision: dev
    helm:
      valueFiles:
        - dev-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

